/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AppStaffManagementRouteImport } from './routes/_app.staff-management'
import { Route as AppStaffRouteImport } from './routes/_app.staff'
import { Route as AppRemindersRouteImport } from './routes/_app.reminders'
import { Route as AppRecordsRouteImport } from './routes/_app.records'
import { Route as AppQueueRouteImport } from './routes/_app.queue'
import { Route as AppPharmacyRouteImport } from './routes/_app.pharmacy'
import { Route as AppPatientsRouteImport } from './routes/_app.patients'
import { Route as AppLabResultsRouteImport } from './routes/_app.lab-results'
import { Route as AppLabRequestsRouteImport } from './routes/_app.lab-requests'
import { Route as AppInventoryRouteImport } from './routes/_app.inventory'
import { Route as AppInsightsRouteImport } from './routes/_app.insights'
import { Route as AppFrontDeskRouteImport } from './routes/_app.front-desk'
import { Route as AppFoundFamilyRouteImport } from './routes/_app.found-family'
import { Route as AppDoctorsRouteImport } from './routes/_app.doctors'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppChatRouteImport } from './routes/_app.chat'
import { Route as AppBillingCenterRouteImport } from './routes/_app.billing-center'
import { Route as AppBillingRouteImport } from './routes/_app.billing'
import { Route as AppAppointmentsRouteImport } from './routes/_app.appointments'
import { Route as AppAdminRecordsRouteImport } from './routes/_app.admin-records'
import { Route as AppAdminBillingRouteImport } from './routes/_app.admin-billing'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffManagementRoute = AppStaffManagementRouteImport.update({
  id: '/staff-management',
  path: '/staff-management',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffRoute = AppStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AppRoute,
} as any)
const AppRemindersRoute = AppRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => AppRoute,
} as any)
const AppRecordsRoute = AppRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => AppRoute,
} as any)
const AppQueueRoute = AppQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AppRoute,
} as any)
const AppPharmacyRoute = AppPharmacyRouteImport.update({
  id: '/pharmacy',
  path: '/pharmacy',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientsRoute = AppPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AppRoute,
} as any)
const AppLabResultsRoute = AppLabResultsRouteImport.update({
  id: '/lab-results',
  path: '/lab-results',
  getParentRoute: () => AppRoute,
} as any)
const AppLabRequestsRoute = AppLabRequestsRouteImport.update({
  id: '/lab-requests',
  path: '/lab-requests',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppRoute,
} as any)
const AppFrontDeskRoute = AppFrontDeskRouteImport.update({
  id: '/front-desk',
  path: '/front-desk',
  getParentRoute: () => AppRoute,
} as any)
const AppFoundFamilyRoute = AppFoundFamilyRouteImport.update({
  id: '/found-family',
  path: '/found-family',
  getParentRoute: () => AppRoute,
} as any)
const AppDoctorsRoute = AppDoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingCenterRoute = AppBillingCenterRouteImport.update({
  id: '/billing-center',
  path: '/billing-center',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppAppointmentsRoute = AppAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRecordsRoute = AppAdminRecordsRouteImport.update({
  id: '/admin-records',
  path: '/admin-records',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminBillingRoute = AppAdminBillingRouteImport.update({
  id: '/admin-billing',
  path: '/admin-billing',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin-billing': typeof AppAdminBillingRoute
  '/admin-records': typeof AppAdminRecordsRoute
  '/appointments': typeof AppAppointmentsRoute
  '/billing': typeof AppBillingRoute
  '/billing-center': typeof AppBillingCenterRoute
  '/chat': typeof AppChatRoute
  '/dashboard': typeof AppDashboardRoute
  '/doctors': typeof AppDoctorsRoute
  '/found-family': typeof AppFoundFamilyRoute
  '/front-desk': typeof AppFrontDeskRoute
  '/insights': typeof AppInsightsRoute
  '/inventory': typeof AppInventoryRoute
  '/lab-requests': typeof AppLabRequestsRoute
  '/lab-results': typeof AppLabResultsRoute
  '/patients': typeof AppPatientsRoute
  '/pharmacy': typeof AppPharmacyRoute
  '/queue': typeof AppQueueRoute
  '/records': typeof AppRecordsRoute
  '/reminders': typeof AppRemindersRoute
  '/staff': typeof AppStaffRoute
  '/staff-management': typeof AppStaffManagementRoute
  '/users': typeof AppUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin-billing': typeof AppAdminBillingRoute
  '/admin-records': typeof AppAdminRecordsRoute
  '/appointments': typeof AppAppointmentsRoute
  '/billing': typeof AppBillingRoute
  '/billing-center': typeof AppBillingCenterRoute
  '/chat': typeof AppChatRoute
  '/dashboard': typeof AppDashboardRoute
  '/doctors': typeof AppDoctorsRoute
  '/found-family': typeof AppFoundFamilyRoute
  '/front-desk': typeof AppFrontDeskRoute
  '/insights': typeof AppInsightsRoute
  '/inventory': typeof AppInventoryRoute
  '/lab-requests': typeof AppLabRequestsRoute
  '/lab-results': typeof AppLabResultsRoute
  '/patients': typeof AppPatientsRoute
  '/pharmacy': typeof AppPharmacyRoute
  '/queue': typeof AppQueueRoute
  '/records': typeof AppRecordsRoute
  '/reminders': typeof AppRemindersRoute
  '/staff': typeof AppStaffRoute
  '/staff-management': typeof AppStaffManagementRoute
  '/users': typeof AppUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_app/admin-billing': typeof AppAdminBillingRoute
  '/_app/admin-records': typeof AppAdminRecordsRoute
  '/_app/appointments': typeof AppAppointmentsRoute
  '/_app/billing': typeof AppBillingRoute
  '/_app/billing-center': typeof AppBillingCenterRoute
  '/_app/chat': typeof AppChatRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/doctors': typeof AppDoctorsRoute
  '/_app/found-family': typeof AppFoundFamilyRoute
  '/_app/front-desk': typeof AppFrontDeskRoute
  '/_app/insights': typeof AppInsightsRoute
  '/_app/inventory': typeof AppInventoryRoute
  '/_app/lab-requests': typeof AppLabRequestsRoute
  '/_app/lab-results': typeof AppLabResultsRoute
  '/_app/patients': typeof AppPatientsRoute
  '/_app/pharmacy': typeof AppPharmacyRoute
  '/_app/queue': typeof AppQueueRoute
  '/_app/records': typeof AppRecordsRoute
  '/_app/reminders': typeof AppRemindersRoute
  '/_app/staff': typeof AppStaffRoute
  '/_app/staff-management': typeof AppStaffManagementRoute
  '/_app/users': typeof AppUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/admin-billing'
    | '/admin-records'
    | '/appointments'
    | '/billing'
    | '/billing-center'
    | '/chat'
    | '/dashboard'
    | '/doctors'
    | '/found-family'
    | '/front-desk'
    | '/insights'
    | '/inventory'
    | '/lab-requests'
    | '/lab-results'
    | '/patients'
    | '/pharmacy'
    | '/queue'
    | '/records'
    | '/reminders'
    | '/staff'
    | '/staff-management'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/admin-billing'
    | '/admin-records'
    | '/appointments'
    | '/billing'
    | '/billing-center'
    | '/chat'
    | '/dashboard'
    | '/doctors'
    | '/found-family'
    | '/front-desk'
    | '/insights'
    | '/inventory'
    | '/lab-requests'
    | '/lab-results'
    | '/patients'
    | '/pharmacy'
    | '/queue'
    | '/records'
    | '/reminders'
    | '/staff'
    | '/staff-management'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_app/admin-billing'
    | '/_app/admin-records'
    | '/_app/appointments'
    | '/_app/billing'
    | '/_app/billing-center'
    | '/_app/chat'
    | '/_app/dashboard'
    | '/_app/doctors'
    | '/_app/found-family'
    | '/_app/front-desk'
    | '/_app/insights'
    | '/_app/inventory'
    | '/_app/lab-requests'
    | '/_app/lab-results'
    | '/_app/patients'
    | '/_app/pharmacy'
    | '/_app/queue'
    | '/_app/records'
    | '/_app/reminders'
    | '/_app/staff'
    | '/_app/staff-management'
    | '/_app/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/staff-management': {
      id: '/_app/staff-management'
      path: '/staff-management'
      fullPath: '/staff-management'
      preLoaderRoute: typeof AppStaffManagementRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/staff': {
      id: '/_app/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AppStaffRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reminders': {
      id: '/_app/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof AppRemindersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/records': {
      id: '/_app/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof AppRecordsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/queue': {
      id: '/_app/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof AppQueueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pharmacy': {
      id: '/_app/pharmacy'
      path: '/pharmacy'
      fullPath: '/pharmacy'
      preLoaderRoute: typeof AppPharmacyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/patients': {
      id: '/_app/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof AppPatientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lab-results': {
      id: '/_app/lab-results'
      path: '/lab-results'
      fullPath: '/lab-results'
      preLoaderRoute: typeof AppLabResultsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lab-requests': {
      id: '/_app/lab-requests'
      path: '/lab-requests'
      fullPath: '/lab-requests'
      preLoaderRoute: typeof AppLabRequestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/insights': {
      id: '/_app/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/front-desk': {
      id: '/_app/front-desk'
      path: '/front-desk'
      fullPath: '/front-desk'
      preLoaderRoute: typeof AppFrontDeskRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/found-family': {
      id: '/_app/found-family'
      path: '/found-family'
      fullPath: '/found-family'
      preLoaderRoute: typeof AppFoundFamilyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/doctors': {
      id: '/_app/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof AppDoctorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing-center': {
      id: '/_app/billing-center'
      path: '/billing-center'
      fullPath: '/billing-center'
      preLoaderRoute: typeof AppBillingCenterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/appointments': {
      id: '/_app/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppAppointmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin-records': {
      id: '/_app/admin-records'
      path: '/admin-records'
      fullPath: '/admin-records'
      preLoaderRoute: typeof AppAdminRecordsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin-billing': {
      id: '/_app/admin-billing'
      path: '/admin-billing'
      fullPath: '/admin-billing'
      preLoaderRoute: typeof AppAdminBillingRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminBillingRoute: typeof AppAdminBillingRoute
  AppAdminRecordsRoute: typeof AppAdminRecordsRoute
  AppAppointmentsRoute: typeof AppAppointmentsRoute
  AppBillingRoute: typeof AppBillingRoute
  AppBillingCenterRoute: typeof AppBillingCenterRoute
  AppChatRoute: typeof AppChatRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDoctorsRoute: typeof AppDoctorsRoute
  AppFoundFamilyRoute: typeof AppFoundFamilyRoute
  AppFrontDeskRoute: typeof AppFrontDeskRoute
  AppInsightsRoute: typeof AppInsightsRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppLabRequestsRoute: typeof AppLabRequestsRoute
  AppLabResultsRoute: typeof AppLabResultsRoute
  AppPatientsRoute: typeof AppPatientsRoute
  AppPharmacyRoute: typeof AppPharmacyRoute
  AppQueueRoute: typeof AppQueueRoute
  AppRecordsRoute: typeof AppRecordsRoute
  AppRemindersRoute: typeof AppRemindersRoute
  AppStaffRoute: typeof AppStaffRoute
  AppStaffManagementRoute: typeof AppStaffManagementRoute
  AppUsersRoute: typeof AppUsersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminBillingRoute: AppAdminBillingRoute,
  AppAdminRecordsRoute: AppAdminRecordsRoute,
  AppAppointmentsRoute: AppAppointmentsRoute,
  AppBillingRoute: AppBillingRoute,
  AppBillingCenterRoute: AppBillingCenterRoute,
  AppChatRoute: AppChatRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDoctorsRoute: AppDoctorsRoute,
  AppFoundFamilyRoute: AppFoundFamilyRoute,
  AppFrontDeskRoute: AppFrontDeskRoute,
  AppInsightsRoute: AppInsightsRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppLabRequestsRoute: AppLabRequestsRoute,
  AppLabResultsRoute: AppLabResultsRoute,
  AppPatientsRoute: AppPatientsRoute,
  AppPharmacyRoute: AppPharmacyRoute,
  AppQueueRoute: AppQueueRoute,
  AppRecordsRoute: AppRecordsRoute,
  AppRemindersRoute: AppRemindersRoute,
  AppStaffRoute: AppStaffRoute,
  AppStaffManagementRoute: AppStaffManagementRoute,
  AppUsersRoute: AppUsersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
